name: Publish NuGet package

on:
  push:
    tags:
      - 'v*'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build project
        run: dotnet build --configuration Release

      - name: Pack NuGet package
        run: dotnet pack --configuration Release --no-build --include-symbols

      - name: Publish NuGet package
        uses: nuget/publish@v1
        with:
          nuget-version: '5.x'
          nuget-api-key: ${{ secrets.NUGET_API_KEY }}
          nuget-package: 'out/*.nupkg'
          nuget-push-options: '--skip-duplicate'