name: Publish NuGet package

on:
  workflow_dispatch:
    inputs:
      git-tag:
        description: 'The version number for the Git tag'
        required: true
        default: 'v1.0.0'
        type: string 

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '6.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build & Pack NuGet package
        shell: pwsh
        run: |
          $version = "${{ inputs.git-tag }}";
          $gitTag = "v$version";
          git tag $gitTag;
          $remote = git remote;
          git push $remote $gitTag;
          dotnet pack src/MeirbDemo.Library --output out --configuration Release --include-symbols -p:Version=$version

      - name: Publish NuGet package
        shell: pwsh
        run: |
          $symbols = Get-ChildItem out/*.symbols.nupkg | ForEach-Object FullName;
          foreach ($symbol in $symbols) {
            Write-Host "Pushing symbols $symbol";
            $nupkg = $symbol.Replace(".symbols.nupkg",".nupkg");
            Write-Host "Pushing nupkg $nupkg";
            dotnet nuget push $nupkg --skip-duplicate --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json;
          }